apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datacater-cluster
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces", "pods", "pods/log", "services", "namespace", "configmaps"]
    verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments", "configmaps", "replicasets"]
    verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
