apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: datacater-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "datacater.serviceAccountName" . }} # Name is case sensitive
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: datacater-cluster
  apiGroup: rbac.authorization.k8s.io
