apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datacater-cluster
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: [ "create", "patch", "update", "list", "watch", "get" ]
