apiVersion: v1
kind: Service
metadata:
  name: "pythonrunner"
  labels:
    {{- include "datacater.labelsPythonRunner" . | nindent 4 }}
spec:
  selector:
      {{- include "datacater.selectorLabelsPythonRunner" . | nindent 4 }}
  ports:
    - name: "http"
      protocol: "TCP"
      port: 50000
      targetPort: 50000
