apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: udf-testing-view
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: datacater-api
subjects:
  - kind: ServiceAccount
    name: {{ include "datacater.serviceAccountName" . }}
