apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datacater-api
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "pods/log", "services", "namespace"]
    verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployment"]
    verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
