apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "datacater.fullname" . }}
  labels:
    {{- include "datacater.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "datacater.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "datacater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datacater.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "datacater.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              value: "postgresql://{{ .Values.datacater.database.host  }}"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: {{ .Values.datacater.database.username | quote }}
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: {{ .Values.datacater.database.password | quote }}
            - name: DATACATER_DEPLOYMENT_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DATACATER_DEPLOYMENT_IMAGE
              value: {{ .Values.datacater.deployment.image | quote }}
            - name: DATACATER_TRANSFORMS_PATH
              value: {{ .Values.datacater.transforms.path | quote }}
            - name: DATACATER_FILTERS_PATH
              value: {{ .Values.datacater.filters.path | quote }}
            - name: DATACATER_PYTHONRUNNER_REPLICAS
              value: {{ .Values.datacater.pythonrunner.replicas | quote }}
            - name: DATACATER_PYTHONRUNNER_IMAGE_NAME
              value: {{ .Values.datacater.pythonrunner.image.version | quote }}
            - name: QUARKUS_LOG_CONSOLE_JSON
              value: "false"
            - name: DATACATER_PYTHONRUNNER_IMAGE_NAMESPACE
              value: {{ $.Release.Namespace | default "default" }}
            - name: DATACATER_PYTHONRUNNER_SERVICENAME
              value: {{ .Values.datacater.pythonrunner.serviceName | quote }}
          {{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.postgres.enabled }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
