apiVersion: v1
kind: Service
metadata:
  name: datacater-ui
  labels:
    {{- include "datacater.labelsUi" . | nindent 4 }}
spec:
  selector:
      {{- include "datacater.selectorLabelsUi" . | nindent 4 }}
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: {{ .Values.datacater.ui.service.type | default "ClusterIp" }}
