apiVersion: apps/v1
kind: Deployment
metadata:
  name: "datacater-ui"
  labels:
    {{- include "datacater.labelsUi" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "datacater.selectorLabelsUi" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "datacater.selectorLabelsUi" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.datacater.ui.image.repository }}:{{ .Values.datacater.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.datacater.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
