apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ui
  name: ui
  namespace: default
spec:
  containers:
    - image: datacater/ui:alpha-20221208
      imagePullPolicy: IfNotPresent
      name: ui
      ports:
        - containerPort: 8080
          protocol: TCP
          name: http
