---
quarkus  :
  application:
    name: pipeline
    version: '1'
  reactive-messaging:
    metrics:
      enabled: true
    kafka:
      enable-graceful-shutdown-in-dev-and-test-mode: true
  container-image:
    group: datacater
    name: ${quarkus.application.name}
    tag: ${quarkus.application.version}
    http:
      cors: true
mp       :
  messaging:
    outgoing:
      streamout:
        merge: true
        connector: smallrye-kafka
        topic: streamout
    incoming:
      streamin:
        batch: true
        connector: smallrye-kafka
        max:
          poll:
            records: ${datacater.message.batch.size}
        topic: streamin
datacater:
  python-runner:
    port: 50000
    host: localhost
    version: alpha-20221129
    protocol: file
  message:
    batch:
      size: 2500

'%dev'   :
  quarkus:
    log:
      level: INFO
      console:
        json: false
  datacater:
    python-runner:
      port: 50000
      host: localhost
      version: alpha-20221129
      protocol: http

'%test'  :
  datacater:
    python-runner:
      protocol: http
      version: alpha-20221129
  quarkus:
    log:
      level: INFO
      console:
        json: false
  mp:
    messaging:
      outgoing:
        streamin-test:
          connector: smallrye-kafka
          topic: streamin
      incoming:
        streamout-test:
          connector: smallrye-kafka
          topic: streamout
          key:
            deserializer: io.datacater.core.serde.JsonDeserializer
          value:
            deserializer: io.datacater.core.serde.JsonDeserializer
