---
quarkus  :
  application:
    name: pipeline
    version: '1'
  reactive-messaging:
    metrics:
      enabled: true
    kafka:
      enable-graceful-shutdown-in-dev-and-test-mode: true
  container-image:
    group: datacater
    name: ${quarkus.application.name}
    tag: ${quarkus.application.version}
    http:
      cors: true
mp       :
  messaging:
    outgoing:
      stream-out:
        merge: true
        connector: smallrye-kafka
        kafka-configuration: stream-out-configuration
        max-inflight-messages: 0
        topic: stream-out
        waitForWriteCompletion: false
    incoming:
      stream-in:
        auto.commit.interval.ms: 10000
        batch: true
        connector: smallrye-kafka
        commit-strategy: throttled
        fetch.min.bytes: 102400
        max:
          poll:
            records: ${datacater.message.batch.size}
        kafka-configuration: stream-in-configuration
        topic: stream-in
datacater:
  python-runner:
    port: 50000
    host: localhost
    version: alpha-20221129
    protocol: file
  message:
    batch:
      size: 2500
  stream-in:
    config: '{"key.deserializer": "io.datacater.core.serde.JsonDeserializer", "value.deserializer": "io.datacater.core.serde.JsonDeserializer"}'
  stream-out:
    config: '{"key.serializer": "io.datacater.core.serde.JsonSerializer", "value.serializer": "io.datacater.core.serde.JsonSerializer"}'


'%dev'   :
  quarkus:
    log:
      level: INFO
      console:
        json: false
  datacater:
    python-runner:
      port: 50000
      host: localhost
      version: alpha-20221129
      protocol: http

'%test'  :
  datacater:
    python-runner:
      protocol: http
      version: alpha-20221129
  quarkus:
    log:
      level: INFO
      console:
        json: false
  mp:
    messaging:
      outgoing:
        stream-in-test:
          connector: smallrye-kafka
          topic: stream-in
      incoming:
        stream-out-test:
          connector: smallrye-kafka
          topic: stream-out
          key:
            deserializer: io.datacater.core.serde.JsonDeserializer
          value:
            deserializer: io.datacater.core.serde.JsonDeserializer
